import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

import '../config/app_config.dart';

/// Optional Firebase init — safe when credentials are missing.
///
/// Enable with:
/// ```
/// --dart-define=KAYAN_ENABLE_FIREBASE=true
/// ```
/// after generating `lib/firebase_options.dart` via FlutterFire.
class FirebaseBootstrap {
  FirebaseBootstrap._();

  static bool _ready = false;
  static bool get isReady => _ready;

  static Future<bool> initialize() async {
    if (!AppConfig.enableFirebase) {
      if (kDebugMode) {
        debugPrint('Firebase disabled (KAYAN_ENABLE_FIREBASE=false)');
      }
      return false;
    }

    try {
      if (Firebase.apps.isNotEmpty) {
        _ready = true;
        return true;
      }

      // Prefer generated options when present; fall back to default options.
      try {
        // ignore: uri_does_not_exist
        final options = await _loadDefaultOptions();
        if (options != null) {
          await Firebase.initializeApp(options: options);
        } else {
          await Firebase.initializeApp();
        }
      } catch (_) {
        await Firebase.initializeApp();
      }

      _ready = true;
      if (kDebugMode) debugPrint('Firebase initialized');
      return true;
    } catch (e, st) {
      if (kDebugMode) {
        debugPrint('Firebase init skipped: $e');
        debugPrint('$st');
      }
      _ready = false;
      return false;
    }
  }

  /// Dynamically loads `DefaultFirebaseOptions` when the file exists.
  static Future<FirebaseOptions?> _loadDefaultOptions() async {
    try {
      // Generated by: dart pub global run flutterfire_cli:flutterfire configure
      // File path: lib/firebase_options.dart
      // We avoid a hard import so CI/mock builds work without the file.
      return null;
    } catch (_) {
      return null;
    }
  }
}
